version: '3.8'

services:
  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_URI=
      - PORT=8082
      - JWT_SECRET_KEY=

  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - auth-service
    environment:
      - DB_URI=
      - PORT=9000
      - JWT_SECRET_KEY=
      - KAFKA_CLIENT_ID=
      - KAFKA_BROKERS=
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
      - KAFKA_GROUP_ID=
      - KAFKA_TOPICS=

  realtime-service:
    build:
      context: ./realtime-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
      - "8000:8000"
    depends_on:
      - notification-service
    environment:
      - DB_URI=
      - PORT=9001
      - JWT_SECRET_KEY=
      - WS_PORT=8000
      - KAFKA_CLIENT_ID=
      - KAFKA_BROKERS=
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
