version: '3.8'

services:
  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_URI=${DB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DB_URI=${DB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_GROUP_ID=notification-group
      - KAFKA_TOPICS=${KAFKA_TOPICS}

  realtime-service:
    build:
      context: ./realtime-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
      - "8000:8000"
    environment:
      - DB_URI=${DB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - WS_PORT=8000
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
