# Dockerfile for auth-service
FROM node:20

# Create app directory
WORKDIR /src/app

# Install app dependencies
COPY package*.json ./

RUN yarn install

# Copy app source code
COPY . .

# Expose the port
EXPOSE 8082

# Start the app
CMD ["npm", "run","dev"]
